src/Orchard.Web/Modules/Orchard.Localization/Controllers/AdminController.cs
using System;
using System.Web.Mvc;
using Orchard.ContentManagement;
using Orchard.ContentManagement.Aspects;
using Orchard.Core.Contents.Settings;
using Orchard.DisplayManagement;
using Orchard.Localization.Models;
using Orchard.Localization.Services;
using Orchard.Localization.ViewModels;
using Orchard.Mvc;
using Orchard.UI.Notify;

namespace Orchard.Localization.Controllers {
    [ValidateInput(false)]
    public class AdminController : Controller, IUpdateModel {
        private readonly IContentManager _contentManager;
        private readonly ILocalizationService _localizationService;

        public AdminController(
            IOrchardServices orchardServices,
            IContentManager contentManager,
            ILocalizationService localizationService,
            IShapeFactory shapeFactory) {
            _contentManager = contentManager;
            _localizationService = localizationService;
            T = NullLocalizer.Instance;
            Services = orchardServices;
            Shape = shapeFactory;
        }

        dynamic Shape { get; set; }
        public Localizer T { get; set; }
        public IOrchardServices Services { get; set; }

        public ActionResult Translate(int id, string to) {
            var masterContentItem = _contentManager.Get(id, VersionOptions.Latest);
            if (masterContentItem == null)
                return HttpNotFound();

            var masterLocalizationPart = masterContentItem.As<LocalizationPart>();
            if (masterLocalizationPart == null)
                return HttpNotFound();

            // Check is current item stll exists, and redirect.
            var existingTranslation = _localizationService.GetLocalizedContentItem(masterContentItem, to);
            if (existingTranslation != null) {
                var existingTranslationMetadata = _contentManager.GetItemMetadata(existingTranslation);
                return RedirectToAction(
                    Convert.ToString(existingTranslationMetadata.EditorRouteValues["action"]),
                    existingTranslationMetadata.EditorRouteValues);
            }

            var contentItemTranslation = _contentManager.New<LocalizationPart>(masterContentItem.ContentType);
            contentItemTranslation.MasterContentItem = masterContentItem;

            var content = _contentManager.BuildEditor(contentItemTranslation);
            
            return View(content);
        }

        [HttpPost, ActionName("Translate")]
        [FormValueRequired("submit.Save")]
        public ActionResult TranslatePOST(int id) {
            return TranslatePOST(id, contentItem => {
                if (!contentItem.Has<IPublishingControlAspect>() && !contentItem.TypeDefinition.Settings.GetModel<ContentTypeSettings>().Draftable)
                    Services.ContentManager.Publish(contentItem);
            });
        }

        [HttpPost, ActionName("Translate")]
        [FormValueRequired("submit.Publish")]
        public ActionResult TranslateAndPublishPOST(int id) {
            return TranslatePOST(id, contentItem => Services.ContentManager.Publish(contentItem));
        }

        public ActionResult TranslatePOST(int id, Action<ContentItem> conditionallyPublish) {
            var masterContentItem = _contentManager.Get(id, VersionOptions.Latest);
            if (masterContentItem == null)
                return HttpNotFound();

            var masterLocalizationPart = masterContentItem.As<LocalizationPart>();
            if (masterLocalizationPart == null)
                return HttpNotFound();

            var model = new EditLocalizationViewModel();
            TryUpdateModel(model, "Localization");

            var existingTranslation = _localizationService.GetLocalizedContentItem(masterContentItem, model.SelectedCulture);
            if (existingTranslation != null) {
                var existingTranslationMetadata = _contentManager.GetItemMetadata(existingTranslation);
                return RedirectToAction(
                    Convert.ToString(existingTranslationMetadata.EditorRouteValues["action"]), 
                    existingTranslationMetadata.EditorRouteValues);
            }

            var contentItemTranslation = _contentManager
                .Create<LocalizationPart>(masterContentItem.ContentType, VersionOptions.Draft, part => {
                    part.MasterContentItem = masterContentItem;
            });

            var content = _contentManager.UpdateEditor(contentItemTranslation, this);

            if (!ModelState.IsValid) {
                Services.TransactionManager.Cancel();

                return View(content);
            }

            conditionallyPublish(contentItemTranslation.ContentItem);

            Services.Notifier.Information(T("Created content item translation."));

            var metadata = _contentManager.GetItemMetadata(contentItemTranslation);
            return RedirectToAction(Convert.ToString(metadata.EditorRouteValues["action"]), metadata.EditorRouteValues);
        }

        bool IUpdateModel.TryUpdateModel<TModel>(TModel model, string prefix, string[] includeProperties, string[] excludeProperties) {
            return TryUpdateModel(model, prefix, includeProperties, excludeProperties);
        }

        void IUpdateModel.AddModelError(string key, LocalizedString errorMessage) {
            ModelState.AddModelError(key, errorMessage.ToString());
        }
    }
}

src/Orchard.Web/Modules/Orchard.Localization/Views/EditorTemplates/Parts/Localization.ContentTranslations.Edit.cshtml
@model Orchard.Localization.ViewModels.EditLocalizationViewModel
@using System.Globalization
@{
    Style.Require("LocalizationAdmin");
}
<fieldset class="localization culture-selection">
    <label for="@Html.FieldIdFor(m => m.SelectedCulture)">@T("Content Localization")</label>
    <div>
        @*Brand new content item*@
        @if (Model.ContentItem.ContentItem.Id == 0) {
            if (Model.MasterContentItem == null) {
                @T("This is the <em>{0}</em> variation of the content",
                    BuildSelectedCultureList(
                        Html.FieldIdFor(m => m.SelectedCulture),
                        Html.FieldNameFor(m => m.SelectedCulture),
                        Model.MissingCultures,
                        Model.SelectedCulture))
            }
            else {
                @T("This is the <em>{0}</em> variation of {1}",
                    BuildSelectedCultureList(
                        Html.FieldIdFor(m => m.SelectedCulture),
                        Html.FieldNameFor(m => m.SelectedCulture),
                        Model.MissingCultures,
                        Model.SelectedCulture),
                    Html.ItemEditLink(Model.MasterContentItem))
            }
        }

        @if (Model.ContentItem.ContentItem.Id > 0) {
            if (string.IsNullOrEmpty(Model.SelectedCulture)) {
                @T("This content currently has no culture associated to it, please select a culture to associate to this piece of content: {0}",
                    BuildSelectedCultureList(
                        Html.FieldIdFor(m => m.SelectedCulture),
                        Html.FieldNameFor(m => m.SelectedCulture),
                        Model.MissingCultures,
                        Model.SelectedCulture))
            }
            else {
                @T("This is the <em>{0}</em> variation of the content",
                    Html.Encode(Model.SelectedCulture))

                if (Model.ContentLocalizations.Localizations.Any()) {
                    <dl class="content-localization">
                        <dt>@T("Other translations:")</dt>
                        <dd class="content-localizations">
                            @Html.UnorderedList(Model.ContentLocalizations.Localizations, (c, i) =>
                                Html.ItemEditLink(c.Culture.Culture, c), "localizations")
                        </dd>
                    </dl>
                }

                if (Model.MissingCultures.Any()) {
                    var contentItemId = Model.MasterContentItem != null ? Model.MasterContentItem.Id : Model.ContentItem.Id;

                    <div class="add-localization">@Html.ActionLink(T("+ New translation").Text, "Translate", "Admin", new {area = "Orchard.Localization", id = contentItemId}, null)</div>
                }

                @Html.Hidden(Html.FieldNameFor(m => m.SelectedCulture), Model.SelectedCulture)
            }
        }
    </div>
</fieldset>



@functions{
    private IHtmlString BuildSelectedCultureList(string id, string name, IEnumerable<string> siteCultures, string culture) {
        TagBuilder selectTag = new TagBuilder("select");
        selectTag.Attributes["id"] = id;
        selectTag.Attributes["name"] = name;

        foreach (var siteCulture in siteCultures) {
            TagBuilder optionTag = new TagBuilder("option");
            optionTag.Attributes["data-content-dir"] = CultureInfo.GetCultureInfo(siteCulture).TextInfo.IsRightToLeft ? "rtl" : "ltr";

            if (siteCulture == culture) {
                optionTag.Attributes["selected"] = "selected";
            }
            optionTag.SetInnerText(Html.Encode(siteCulture));
            selectTag.InnerHtml += optionTag.ToString();
        }

        return Html.Raw(selectTag);
    }
}
@using (Script.Foot()) {
    <script type="text/javascript">
//<![CDATA[
    (function($) {
        "use strict";

        var culture = $("#@Html.FieldIdFor(m => m.SelectedCulture)");

        function flipCulture() {
            var optionDirectionality = $("option:selected", culture).attr("data-content-dir");
            var contentZone = $(".zone-content");
            if (contentZone.hasClass(optionDirectionality))
                return;

            var oldClass = optionDirectionality === "ltr" ? "rtl" : "";

            contentZone.removeClass("content-" + oldClass);
            contentZone.addClass("content-" + optionDirectionality);

            $(document).trigger("localization.ui.directionalitychanged", optionDirectionality);
        }

        culture.change(function () {
            flipCulture();
        });

        flipCulture();
    })(jQuery);
//]]>
    </script>
}